options:
  logging: 'CLOUD_LOGGING_ONLY'
  # Simplified build for quick deployment
  machineType: 'E2_HIGHCPU_8' # 8 vCPUs, 8GB RAM

steps:
# 1. Build the frontend image directly
- id: "Build frontend image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '-f', 'frontend/Dockerfile',
         '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/samaanai-repo/${_FRONTEND_SERVICE_NAME}', 
         '--build-arg', 'ENVIRONMENT=production',
         '--build-arg', 'REACT_APP_API_URL=${_BACKEND_SERVICE_URL}/api',
         '--target', 'prod',
         '.']

# 2. Push the image
- id: "Push frontend image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/samaanai-repo/${_FRONTEND_SERVICE_NAME}']

# 3. Deploy to Cloud Run
- id: "Deploy to Cloud Run"
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_FRONTEND_SERVICE_NAME}'
    - '--image=us-west1-docker.pkg.dev/$PROJECT_ID/samaanai-repo/${_FRONTEND_SERVICE_NAME}'
    - '--platform=managed'
    - '--region=${_REGION}'
    - '--allow-unauthenticated'
    - '--set-env-vars=BUILD_ID=$BUILD_ID,COMMIT_SHA=$COMMIT_SHA'

# 4. Notify about deployment
- id: "Deployment notification"
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🚀 Frontend deployed successfully!"
      echo "🌐 Service URL: https://${_FRONTEND_SERVICE_NAME}-$PROJECT_NUMBER.${_REGION}.run.app"

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/samaanai-repo/${_FRONTEND_SERVICE_NAME}'

substitutions:
  _FRONTEND_SERVICE_NAME: 'samaanai-frontend'
  _REGION: 'us-west1' # Should match backend region
  _BACKEND_SERVICE_URL: 'https://samaanai-backend-1074693546571.us-west1.run.app' # Actual backend URL

timeout: '1200s' # 20 minutes for build and deploy
