options:
  logging: 'CLOUD_LOGGING_ONLY'
  # Increase machine type if tests/builds are slow or run out of memory
  # machineType: 'E2_HIGHCPU_8' # Example: 8 vCPUs, 8GB RAM

steps:
# 1. Run frontend unit tests
- name: 'gcr.io/cloud-builders/docker'
  args: ['compose', '-f', 'docker-compose.test.yml', 'run', '--rm', 'frontend-test', 'npm', 'test', '--', '--ci', '--passWithNoTests']

# 2. Run E2E (Cypress) tests
- name: 'gcr.io/cloud-builders/docker'
  args: ['compose', '-f', 'docker-compose.test.yml', 'run', '--rm', 'cypress']

# 3. Build the frontend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/samaanai-repo/${_FRONTEND_SERVICE_NAME}', 
         '--build-arg', 'ENVIRONMENT=production',
         '--build-arg', 'REACT_APP_API_URL=${_BACKEND_SERVICE_URL}/api',
         '--target', 'prod',
         './frontend']

# 4. Push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/samaanai-repo/${_FRONTEND_SERVICE_NAME}']

# 5. Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_FRONTEND_SERVICE_NAME}'
    - '--image=us-west1-docker.pkg.dev/$PROJECT_ID/samaanai-repo/${_FRONTEND_SERVICE_NAME}'
    - '--platform=managed'
    - '--region=${_REGION}'
    - '--allow-unauthenticated'

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/samaanai-repo/${_FRONTEND_SERVICE_NAME}'

substitutions:
  _FRONTEND_SERVICE_NAME: 'samaanai-frontend'
  _REGION: 'us-west1' # Should match backend region
  _BACKEND_SERVICE_URL: 'https://samaanai-backend-1074693546571.us-west1.run.app' # Actual backend URL

timeout: '1200s' # 20 minutes
