# Generated by Django 4.2.21 on 2025-06-02 02:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('budget_alerts', models.BooleanField(default=True)),
                ('low_balance_alerts', models.BooleanField(default=True)),
                ('new_transaction_alerts', models.BooleanField(default=False)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('monthly_reports', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('budget_threshold', models.IntegerField(default=90, help_text='Percentage of budget to trigger alert', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=100.0, help_text='Dollar amount to trigger low balance alert', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('budget_alert', 'Budget Alert'), ('low_balance', 'Low Balance Alert'), ('new_transaction', 'New Transaction'), ('weekly_report', 'Weekly Report'), ('monthly_report', 'Monthly Report'), ('security_alert', 'Security Alert'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('subject', models.CharField(max_length=200)),
                ('template_name', models.CharField(max_length=100)),
                ('context_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_103f8a_idx'), models.Index(fields=['user', 'email_type'], name='notificatio_user_id_895bff_idx'), models.Index(fields=['priority'], name='notificatio_priorit_b36c80_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('budget_alert', 'Budget Alert'), ('low_balance', 'Low Balance Alert'), ('new_transaction', 'New Transaction'), ('weekly_report', 'Weekly Report'), ('monthly_report', 'Monthly Report'), ('security_alert', 'Security Alert'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'email_type'], name='notificatio_user_id_f02660_idx'), models.Index(fields=['sent_at'], name='notificatio_sent_at_428e78_idx'), models.Index(fields=['success'], name='notificatio_success_7fb2da_idx')],
            },
        ),
    ]
