# Generated by Django 4.2.20 on 2025-05-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='start_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Preferred day to start the week'),
        ),
    ]
