# Generated by Django 4.2.21 on 2025-05-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_start_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('US/Pacific', 'Pacific Time (PT)'), ('US/Mountain', 'Mountain Time (MT)'), ('US/Central', 'Central Time (CT)'), ('US/Eastern', 'Eastern Time (ET)'), ('UTC', 'UTC'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris'), ('Asia/Tokyo', 'Tokyo'), ('Australia/Sydney', 'Sydney')], default='US/Pacific', help_text='Your local timezone', max_length=50),
        ),
    ]
