# Generated by Django 4.2.21 on 2025-06-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sync_cursor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
