# Generated by Django 4.2.21 on 2025-06-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_institution_sync_cursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
