# Generated by Codex

from django.db import migrations

from apps.finance.fields import EncryptedTextField


def encrypt_existing_tokens(apps, schema_editor):
    Institution = apps.get_model('finance', 'Institution')
    field = EncryptedTextField()
    field.set_attributes_from_name('access_token')

    for institution in Institution.objects.exclude(access_token__isnull=True).iterator():
        token = institution.access_token
        if not token:
            continue
        encrypted = field.get_prep_value(token)
        Institution.objects.filter(pk=institution.pk).update(access_token=encrypted)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_holding_investmenttransaction_security_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='access_token',
            field=EncryptedTextField(),
        ),
        migrations.RunPython(encrypt_existing_tokens, noop_reverse),
    ]
