# Generated by Django 4.2.27 on 2025-12-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_encrypt_institution_access_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
