# Generated by Django 4.2.27 on 2025-12-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_is_manual_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exclude_from_reports',
            field=models.BooleanField(default=False),
        ),
    ]
