# Generated by Django 4.2.27 on 2026-01-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_exclude_from_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
