# Generated by Django 4.2.27 on 2026-01-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_custom_name_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.spendingcategory'),
        ),
    ]
