# Generated by Django 4.2.20 on 2025-05-07 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AlterModelOptions(
            name='exerciseentry',
            options={'ordering': ['-date', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='mealentry',
            options={'ordering': ['-date', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='exerciseentry',
            name='daily_entry',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='daily_entry',
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DailyEntry',
        ),
    ]
