# Generated by Django 4.2.20 on 2025-05-09 02:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0002_weightentry_alter_exerciseentry_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealentry',
            unique_together={('user', 'date', 'meal_type')},
        ),
    ]
