# Generated by Django 4.2.20 on 2025-05-09 02:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0003_alter_mealentry_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciseentry',
            unique_together={('user', 'date')},
        ),
    ]
