# Generated by Django 4.2.21 on 2025-05-24 19:11

import apps.nutrition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_exerciseentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseentry',
            name='date',
            field=models.DateField(default=apps.nutrition.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='date',
            field=models.DateField(default=apps.nutrition.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=apps.nutrition.models.get_current_date),
        ),
    ]
